### ISSUE TITLE
Crashes Apon Startup

### ISSUE THREAD

**Issue by GWCJ** [LordNed/Winditor#27]
I don't why but when I was setting up Winditior it crashed and now crashes apon startup

**Comment by GWCJ** [comment]
oh
----------------------------------------
Winditor crashed on: 10/15/2021 21:24:58

System.NotImplementedException
Unknown magic: 4C696E6B. If this is a Nintendo archive, open an Issue on GitHub!
   at WArchiveTools.ArchiveUtilities.LoadArchive(String filePath) in D:\WW\Winditor\WArchive-Tools\ArchiveToolsLib\ArcUtilities.cs:line 58
   at WindEditor.WWindEditor.OnApplicationRequestOpenRooms() in D:\WW\Winditor\Editor\Editor\Modes\WindEditor.cs:line 204
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at WindEditor.App.Main()

----------------------------------------
Winditor crashed on: 10/15/2021 21:36:56

System.IO.EndOfStreamException
Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at JStudio.J3D.J3D.LoadTagDataFromFile(EndianBinaryReader reader, Int32 tagCount, Boolean dumpTextures, Boolean dumpShaders) in D:\WW\Winditor\JStudio\JStudio\J3D\J3D.cs:line 411
   at JStudio.J3D.J3D.LoadFromStream(EndianBinaryReader reader, Boolean dumpTextures, Boolean dumpShaders) in D:\WW\Winditor\JStudio\JStudio\J3D\J3D.cs:line 130
   at WindEditor.WResourceManager.LoadResource(String filePath) in D:\WW\Winditor\Editor\Editor\Managers\ResourceManager.cs:line 562
   at WindEditor.WScene.LoadModel(String rootFolder, String modelName) in D:\WW\Winditor\Editor\Editor\Maps\Scene.cs:line 131
   at WindEditor.WRoom.LoadRoomModels(String filePath) in D:\WW\Winditor\Editor\Editor\Maps\Room.cs:line 125
   at WindEditor.WRoom.Load(String filePath) in D:\WW\Winditor\Editor\Editor\Maps\Room.cs:line 86
   at WindEditor.WMap.LoadFromDirectory(String inPath, String sourcePath) in D:\WW\Winditor\Editor\Editor\Maps\Map.cs:line 83
   at WindEditor.WWorld.LoadMapFromDirectory(String folderPath, String sourcePath) in D:\WW\Winditor\Editor\Editor\Maps\World.cs:line 156
   at WindEditor.WWindEditor.OnApplicationRequestOpenProject() in D:\WW\Winditor\Editor\Editor\Modes\WindEditor.cs:line 139
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at WindEditor.App.Main()

**Comment by LagoLunatic** [comment]
What stage did you open? If it was an unused stage, it might just not be valid and you can't open it

**Comment by GWCJ** [comment]
i didn't even open a stage. i was editing and it just started crashing

**Comment by LagoLunatic** [comment]
So it crashes when launching Winditor, before opening a map? And it didn't used to do that, it only started after using it a few times to edit maps?

Then I guess your settings.json file got corrupted somehow, upload that file.
